baseURL = "https://takle-mamo.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Takle mamo"
theme = "FeelIt"
enableRobotsTXT = true

[languages]
  [language.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4

[params]
  # FeelIt theme version
  version = "1.0.X"
  description = "Malo o tem in onem. Takle mamo ..."
  keywords = ["IVF"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  # whether to enable CSS and JS source mapping
  SourceMap = false

  [params.pwa]
    # whether to enable PWA support
    enable = true
    # service-worker version
    version = "1.0.1"

  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    [params.header.title]
      name = "Takle mamo"
      typeit = false
      rss = true

  [params.footer]
    copyright = true
    author = true
    since = 2021
    hugo = false

  # Section (all posts) page config
  [params.section]
    paginate = 20

  [params.about]
    enable = true
    description = "Takle mamo"

  [params.home]
    [params.home.posts]
      enable = true
      paginate = 6
      imagePreview = true

  [params.social]
    Facebook = "helena.golja"

  [params.page]
    twemoji = false
    fontawesome = true
    cdnfontawesome = true
    linkToMarkdown = false
    lightgallery = false
    
    [params.page.toc]
      enable = false

    [params.page.math]
      enable = false

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true

    [params.page.comment]
      enable = true

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false

[author]
  name = "Helena"
  link = "/about"

[sitemap]
  changefreq = "weekly"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
